### ISSUE TITLE
Post the BIOS configuration

### ISSUE THREAD

**Issue by Diegorro98** [yusifsalam/hackintosh-desktop#1]
Hi!

I'm doing my first hackintosh and its being a long journey 😅.
I have same processor than you but not graphic card (so I use the iGPU).

Would you mind to post you BIOS configuration? I have an ASUS motherboard too (but I have the z270e strix).

I already have done some BIOS configurations for this, but I just want to be sure that we have the same configurations

**Comment by yusifsalam** [comment]
Hi!

You can check BIOS settings from [here](https://dortania.github.io/OpenCore-Install-Guide/config.plist/kaby-lake.html#intel-bios-settings). Not all of those settings are found in ASUS motherboards but if you match most of them, it should be good enough.
